import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import globals from 'globals';

export default [
    {
        ignores: ['dist/**', 'node_modules/**', 'coverage/**', '*.config.ts', '*.config.js'],
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    {
        files: ['src/**/*.{ts,tsx}'],
        languageOptions: {
            parser: tseslint.parser,
            parserOptions: {
                ecmaVersion: 2020,
                sourceType: 'module',
                ecmaFeatures: { jsx: true },
            },
            globals: {
                ...globals.browser,
                ...globals.node,
                ...globals.es2020,
            },
        },
        plugins: {
            react: reactPlugin,
            'react-hooks': reactHooksPlugin,
        },
        settings: {
            react: { version: '18.2' },
        },
        rules: {
            ...reactPlugin.configs.recommended.rules,
            // React Hooks: only keep the two stable/classic rules. The v7 plugin
            // ships React Compiler lints (cascading renders, preserve-manual-
            // memoization, static-components, set-state-in-effect 등) as errors
            // by default — we don't use React Compiler, so those are noise.
            'react-hooks/rules-of-hooks': 'error',
            'react-hooks/exhaustive-deps': 'warn',
            'react/react-in-jsx-scope': 'off',
            'react/prop-types': 'off',
            'react/display-name': 'off',
            '@typescript-eslint/no-explicit-any': 'error',
            '@typescript-eslint/no-unused-vars': [
                'warn',
                { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
            ],
            '@typescript-eslint/ban-ts-comment': [
                'warn',
                {
                    'ts-expect-error': 'allow-with-description',
                    'ts-ignore': false,
                    'ts-nocheck': true,
                },
            ],
            '@typescript-eslint/no-empty-function': 'off',
            '@typescript-eslint/no-empty-object-type': 'off',
            '@typescript-eslint/no-non-null-assertion': 'off',
            'no-console': ['warn', { allow: ['warn', 'error'] }],
            'no-empty': ['warn', { allowEmptyCatch: true }],
            'no-prototype-builtins': 'off',
            'no-case-declarations': 'off',
            'prefer-const': 'warn',
            'no-useless-escape': 'warn',
        },
    },
    {
        // no-explicit-any freeze (PROGRESS P0-8): the rule is 'error' for all
        // new/modified source, but these 135 files carry pre-existing `any`
        // (737 occurrences) and are grandfathered so only NEW `any` is blocked.
        // v0.4 re-foundation whittles this list down (P4/P5 'any 제거'); remove
        // an entry once its file is `any`-free. Do NOT add new files here.
        files: [
            'src/_stubs/assets.d.ts',
            'src/adapters/next/NextUrlStateAdapter.ts',
            'src/listgrid/api/ApiClient.ts',
            'src/listgrid/api/types.ts',
            'src/listgrid/components/api/Type.ts',
            'src/listgrid/components/fields/ApplyFullAddressFields.tsx',
            'src/listgrid/components/fields/CustomOptionField.tsx',
            'src/listgrid/components/fields/DateField.tsx',
            'src/listgrid/components/fields/EmailField.tsx',
            'src/listgrid/components/fields/FileField.tsx',
            'src/listgrid/components/fields/ImageField.tsx',
            'src/listgrid/components/fields/InlineMapField.tsx',
            'src/listgrid/components/fields/ManyToOneField.tsx',
            'src/listgrid/components/fields/PhoneNumberField.tsx',
            'src/listgrid/components/fields/Preset.tsx',
            'src/listgrid/components/fields/SelectField.tsx',
            'src/listgrid/components/fields/SelectFieldRenderer.tsx',
            'src/listgrid/components/fields/TagField.tsx',
            'src/listgrid/components/fields/TelephoneNumberField.tsx',
            'src/listgrid/components/fields/TextareaField.tsx',
            'src/listgrid/components/fields/TimeField.tsx',
            'src/listgrid/components/fields/XrefPriceMappingField.tsx',
            'src/listgrid/components/fields/abstract/AbstractDateField.tsx',
            'src/listgrid/components/fields/abstract/AbstractManyToOneField.tsx',
            'src/listgrid/components/fields/abstract/CheckButtonValidationField.tsx',
            'src/listgrid/components/fields/abstract/FormField.tsx',
            'src/listgrid/components/fields/abstract/ListableFormField.tsx',
            'src/listgrid/components/fields/abstract/OptionalField.tsx',
            'src/listgrid/components/fields/abstract/__tests__/AbstractDateField.test.ts',
            'src/listgrid/components/fields/abstract/__tests__/AbstractManyToOneField.test.ts',
            'src/listgrid/components/fields/abstract/__tests__/FormField.test.ts',
            'src/listgrid/components/fields/abstract/__tests__/OptionalField.test.ts',
            'src/listgrid/components/fields/address/KakaoMap.tsx',
            'src/listgrid/components/fields/address/PostCodeSelector.tsx',
            'src/listgrid/components/fields/contentasset/components/ContentAssetItemUI.tsx',
            'src/listgrid/components/fields/contentasset/hooks/useContentAsset.ts',
            'src/listgrid/components/fields/filter/DatetimeFilter.tsx',
            'src/listgrid/components/fields/rule/RuleBasedFieldView.tsx',
            'src/listgrid/components/fields/rule/RuleCondition.tsx',
            'src/listgrid/components/fields/rule/RuleFieldRenderer.tsx',
            'src/listgrid/components/fields/rule/Type.ts',
            'src/listgrid/components/fields/view/CardManyToOneView.tsx',
            'src/listgrid/components/fields/view/ManyToOneMultiFilterView.tsx',
            'src/listgrid/components/fields/view/ManyToOneView.tsx',
            'src/listgrid/components/fields/view/SelectBoxManyToOneView.tsx',
            'src/listgrid/components/fields/view/TreeSelectView.tsx',
            'src/listgrid/components/fields/view/XrefAvailableDateMappingView.tsx',
            'src/listgrid/components/fields/view/XrefMappingView.tsx',
            'src/listgrid/components/fields/view/XrefPiceMappingView.tsx',
            'src/listgrid/components/fields/view/XrefPreferMappingView.tsx',
            'src/listgrid/components/fields/view/XrefPriorityMappingView.tsx',
            'src/listgrid/components/form/FieldRenderer.tsx',
            'src/listgrid/components/form/ViewEntityForm.tsx',
            'src/listgrid/components/form/ViewFieldGroup.tsx',
            'src/listgrid/components/form/hooks/useEntityFormAutoSave.ts',
            'src/listgrid/components/form/types/ViewEntityFormTheme.types.ts',
            'src/listgrid/components/helper/FieldRendererHelper.tsx',
            'src/listgrid/components/list/AdvancedSearchForm.tsx',
            'src/listgrid/components/list/AdvancedSearchFormV2.tsx',
            'src/listgrid/components/list/QuickSearchBar.tsx',
            'src/listgrid/components/list/RowItem.tsx',
            'src/listgrid/components/list/ViewFieldSelector.tsx',
            'src/listgrid/components/list/ViewListGrid.tsx',
            'src/listgrid/components/list/hooks/__tests__/useCardSubCollectionData.test.ts',
            'src/listgrid/components/list/hooks/useCardSubCollectionData.ts',
            'src/listgrid/components/list/hooks/useListGridLogic.ts',
            'src/listgrid/components/list/hooks/useQuickSearchBar.ts',
            'src/listgrid/components/list/types/ListGridHeader.types.ts',
            'src/listgrid/components/list/types/RowItem.types.ts',
            'src/listgrid/components/list/types/SubCollectionButtons.type.ts',
            'src/listgrid/components/list/types/ViewListGrid.types.ts',
            'src/listgrid/components/list/ui/CardFieldRenderer.tsx',
            'src/listgrid/components/list/ui/CardFieldSection.tsx',
            'src/listgrid/components/list/ui/CardItem.tsx',
            'src/listgrid/components/list/ui/CardSubCollectionView.tsx',
            'src/listgrid/components/list/ui/EntireChecker.test.tsx',
            'src/listgrid/components/list/ui/EntireChecker.tsx',
            'src/listgrid/components/list/ui/FieldSelector.tsx',
            'src/listgrid/components/list/ui/FilterView.tsx',
            'src/listgrid/components/list/ui/HeaderField.tsx',
            'src/listgrid/components/list/ui/HeaderFieldFilter.tsx',
            'src/listgrid/components/list/ui/InlineSubCollectionView.tsx',
            'src/listgrid/components/list/ui/MemoizedFilterField.tsx',
            'src/listgrid/components/list/ui/SearchBarActions.tsx',
            'src/listgrid/components/list/ui/TableSubCollectionView.tsx',
            'src/listgrid/components/list/ui/ViewListGridSkeleton.tsx',
            'src/listgrid/components/list/ui/ViewRows.tsx',
            'src/listgrid/components/list/ui/__tests__/CardSubCollectionView.test.tsx',
            'src/listgrid/components/list/ui/__tests__/InlineSubCollectionView.test.tsx',
            'src/listgrid/components/list/ui/buttons/PriorityButton.tsx',
            'src/listgrid/components/list/utils/mappedByFieldFilter.test.ts',
            'src/listgrid/components/list/utils/mappedByFieldFilter.ts',
            'src/listgrid/components/revision/RevisionField.tsx',
            'src/listgrid/config/CardSubCollectionField.tsx',
            'src/listgrid/config/Config.test.ts',
            'src/listgrid/config/Config.ts',
            'src/listgrid/config/EntityField.ts',
            'src/listgrid/config/EntityForm.tsx',
            'src/listgrid/config/EntityFormMethod.test.ts',
            'src/listgrid/config/EntityFormMethod.ts',
            'src/listgrid/config/EntityFormTypes.ts',
            'src/listgrid/config/EntityItem.ts',
            'src/listgrid/config/InlineSubCollectionField.tsx',
            'src/listgrid/config/ListGrid.ts',
            'src/listgrid/config/OnChangeEntityForm.test.ts',
            'src/listgrid/config/OnChangeEntityForm.ts',
            'src/listgrid/config/SubCollectionField.tsx',
            'src/listgrid/config/__tests__/CardSubCollectionField.test.ts',
            'src/listgrid/config/__tests__/InlineSubCollectionField.test.ts',
            'src/listgrid/config/form/EntityFormActions.tsx',
            'src/listgrid/config/form/EntityFormBase.tsx',
            'src/listgrid/config/form/EntityFormData.tsx',
            'src/listgrid/config/form/EntityFormExtensions.tsx',
            'src/listgrid/config/form/EntityFormValidation.tsx',
            'src/listgrid/extensions/EntityFormExtension.types.ts',
            'src/listgrid/extensions/FieldExtensions.ts',
            'src/listgrid/form/SearchForm.ts',
            'src/listgrid/form/Type.test.ts',
            'src/listgrid/form/Type.ts',
            'src/listgrid/menu/MenuPermissionChecker.ts',
            'src/listgrid/misc/index.ts',
            'src/listgrid/router/types.ts',
            'src/listgrid/transfer/DataExportService.ts',
            'src/listgrid/transfer/DataImportProcessor.tsx',
            'src/listgrid/transfer/DataImporter.tsx',
            'src/listgrid/transfer/Provider/ExcelProvider.ts',
            'src/listgrid/transfer/Type.ts',
            'src/listgrid/transfer/registry.ts',
            'src/listgrid/ui/UIProvider.tsx',
            'src/listgrid/ui/headless.test.tsx',
            'src/listgrid/ui/headless.tsx',
            'src/listgrid/urlState/UrlStateProvider.tsx',
            'src/listgrid/urlState/types.ts',
            'src/listgrid/utils/StringUtil.test.ts',
            'src/listgrid/utils/lazy.tsx',
        ],
        rules: {
            '@typescript-eslint/no-explicit-any': 'off',
        },
    },
];
